export const routes = {
    login: "/login",
    HelpCenter: "help-center",
    Announcment: "announcement",
    Setting: "settings",
    Team: "Team",
    Tickets: "tickets",
    WidgetAppearance: "widget-appearance",
    WidgetAppearancemessage: "/widget-appearance/widget-message",
    WidgetSetting: "widget-setting",
    CreateTicket:"/tickets/create-ticket",
    WriteHelp:"/help-center/write-help",
    VerifyOtp:"/settings/verify-otp",
    ChangePassword:"/settings/change-password",
}