import chatimg from "../assets/Images/Image.png";
export const inboxuser = [
  {
    id: 101,
    email: "xyz@xyz.com",
    Username: "Benedita Tavares",
    message:
      "Hello! I’m sorry to hear this. Could youshow me a screenshot about what happens?",
    time: "2m ago",
    status: "Active",
    unread: "7",
    msssagestatus: "sent",
    newmsg: true,
  },
  {
    id: 102,
    email: "xyz@xyz.com",
    Username: "Dylan Sandoval",
    message:
      "Hello! I’m sorry to hear this. Could youshow me a screenshot about what happens?",
    time: "2m ago",
    msssagestatus: "seen",
    newmsg: true,
  },
  {
    id: 103,
    email: "xyz@xyz.com",
    Username: "Riley Cooper",
    message:
      "Hello! I’m sorry to hear this. Could youshow me a screenshot about what happens?",
    time: "2m ago",
    status: "Active",
    msssagestatus: "seen",
    newmsg: false,
  },
  {
    id: 104,
    email: "xyz@xyz.com",
    Username: "Quinten Kortum",
    message:
      "Hello! I’m sorry to hear this. Could youshow me a screenshot about what happens?",
    time: "2m ago",
    unread: "3",
    status: "Active",
    newmsg: false,
  },
  {
    id: 105,
    email: "xyz@xyz.com",
    Username: "Clarke Gillebert",
    message:
      "Hello! I’m sorry to hear this. Could youshow me a screenshot about what happens?",
    time: "2m ago",
    unread: "3",
    status: "Active",
    newmsg: false,
  },
  {
    id: 106,
    email: "xyz@xyz.com",
    Username: "Fua Lamba",
    message:
      "Hello! I’m sorry to hear this. Could youshow me a screenshot about what happens?",
    time: "2m ago",
    msssagestatus: "seen",
    newmsg: true,
  },
  {
    id: 107,
    email: "xyz@xyz.com",
    Username: "Dylan Sandoval",
    message:
      "Hello! I’m sorry to hear this. Could youshow me a screenshot about what happens?",
    time: "2m ago",
    msssagestatus: "seen",
    newmsg: true,
  },
  {
    id: 108,
    email: "xyz@xyz.com",
    Username: "Riley Cooper",
    message:
      "Hello! I’m sorry to hear this. Could youshow me a screenshot about what happens?",
    time: "2m ago",
    status: "Active",
    msssagestatus: "seen",
    newmsg: false,
  },
  {
    id: 109,
    email: "xyz@xyz.com",
    Username: "Quinten Kortum",
    message:
      "Hello! I’m sorry to hear this. Could youshow me a screenshot about what happens?",
    time: "2m ago",
    unread: "3",
    status: "Active",
    newmsg: false,
  },
  {
    id: 110,
    email: "xyz@xyz.com",
    Username: "Clarke Gillebert",
    message:
      "Hello! I’m sorry to hear this. Could youshow me a screenshot about what happens?",
    time: "2m ago",
    unread: "3",
    status: "Active",
    newmsg: false,
  },
  {
    id: 111,
    email: "xyz@xyz.com",
    Username: "Fua Lamba",
    message:
      "Hello! I’m sorry to hear this. Could youshow me a screenshot about what happens?",
    time: "2m ago",
    msssagestatus: "seen",
    newmsg: true,
  },
  {
    id: 112,
    email: "xyz@xyz.com",
    Username: "Dylan Sandoval",
    message:
      "Hello! I’m sorry to hear this. Could youshow me a screenshot about what happens?",
    time: "2m ago",
    msssagestatus: "seen",
    newmsg: true,
  },
  {
    id: 113,
    email: "xyz@xyz.com",
    Username: "Riley Cooper",
    message:
      "Hello! I’m sorry to hear this. Could youshow me a screenshot about what happens?",
    time: "2m ago",
    status: "Active",
    msssagestatus: "seen",
    newmsg: false,
  },
  {
    id: 114,
    email: "xyz@xyz.com",
    Username: "Quinten Kortum",
    message:
      "Hello! I’m sorry to hear this. Could youshow me a screenshot about what happens?",
    time: "2m ago",
    unread: "3",
    status: "Active",
    newmsg: false,
  },
  {
    id: 115,
    email: "xyz@xyz.com",
    Username: "Clarke Gillebert",
    message:
      "Hello! I’m sorry to hear this. Could youshow me a screenshot about what happens?",
    time: "2m ago",
    unread: "3",
    status: "Active",
    newmsg: false,
  },
  {
    id: 116,
    email: "xyz@xyz.com",
    Username: "Fua Lamba",
    message:
      "Hello! I’m sorry to hear this. Could youshow me a screenshot about what happens?",
    time: "2m ago",
    msssagestatus: "seen",
    newmsg: true,
  },
  {
    id: 117,
    email: "xyz@xyz.com",
    Username: "Dylan Sandoval",
    message:
      "Hello! I’m sorry to hear this. Could youshow me a screenshot about what happens?",
    time: "2m ago",
    msssagestatus: "seen",
    newmsg: true,
  },
  {
    id: 118,
    email: "xyz@xyz.com",
    Username: "Riley Cooper",
    message:
      "Hello! I’m sorry to hear this. Could youshow me a screenshot about what happens?",
    time: "2m ago",
    status: "Active",
    msssagestatus: "seen",
    newmsg: false,
  },
  {
    id: 119,
    email: "xyz@xyz.com",
    Username: "Quinten Kortum",
    message:
      "Hello! I’m sorry to hear this. Could youshow me a screenshot about what happens?",
    time: "2m ago",
    unread: "3",
    status: "Active",
    newmsg: false,
  },
  {
    id: 120,
    email: "xyz@xyz.com",
    Username: "Clarke Gillebert",
    message:
      "Hello! I’m sorry to hear this. Could youshow me a screenshot about what happens?",
    time: "2m ago",
    unread: "3",
    status: "Active",
    newmsg: false,
  },
  {
    id: 121,
    email: "xyz@xyz.com",
    Username: "Fua Lamba",
    message:
      "Hello! I’m sorry to hear this. Could youshow me a screenshot about what happens?",
    time: "2m ago",
    msssagestatus: "seen",
    newmsg: true,
  },
  {
    id: 122,
    email: "xyz@xyz.com",
    Username: "Dylan Sandoval",
    message:
      "Hello! I’m sorry to hear this. Could youshow me a screenshot about what happens?",
    time: "2m ago",
    msssagestatus: "seen",
    newmsg: true,
  },
  {
    id: 123,
    email: "xyz@xyz.com",
    Username: "Riley Cooper",
    message:
      "Hello! I’m sorry to hear this. Could youshow me a screenshot about what happens?",
    time: "2m ago",
    status: "Active",
    msssagestatus: "seen",
    newmsg: false,
  },
  {
    id: 124,
    email: "xyz@xyz.com",
    Username: "Quinten Kortum",
    message:
      "Hello! I’m sorry to hear this. Could youshow me a screenshot about what happens?",
    time: "2m ago",
    unread: "3",
    status: "Active",
    newmsg: false,
  },
  {
    id: 125,
    email: "xyz@xyz.com",
    Username: "Clarke Gillebert",
    message:
      "Hello! I’m sorry to hear this. Could youshow me a screenshot about what happens?",
    time: "2m ago",
    unread: "3",
    status: "Active",
    newmsg: false,
  },
  {
    id: 126,
    email: "xyz@xyz.com",
    Username: "Fua Lamba",
    message:
      "Hello! I’m sorry to hear this. Could youshow me a screenshot about what happens?",
    time: "2m ago",
    msssagestatus: "seen",
    newmsg: true,
  },
  {
    id: 127,
    email: "xyz@xyz.com",
    Username: "Gladys Kanyinda",
    message:
      "Hello! I’m sorry to hear this. Could youshow me a screenshot about what happens?",
    time: "2m ago",
    unread: "3",
    status: "Active",
    newmsg: false,
  },
  {
    id: 128,
    email: "xyz@xyz.com",
    Username: "Jurrien Oldhof",
    message:
      "Hello! I’m sorry to hear this. Could youshow me a screenshot about what happens?",
    time: "2m ago",
    unread: "3",
    newmsg: false,
  },
  {
    id: 129,
    email: "xyz@xyz.com",
    Username: "Marco Alves",
    message:
      "Hello! I’m sorry to hear this. Could youshow me a screenshot about what happens?",
    time: "2m ago",
    unread: "3",
    status: "Active",
    newmsg: true,
  },
];

export const chatboxmessage = [
  {
    id: 123,
    name: "Benedita Tavares",
    message: "Hello! I think I found a bug!",
    message_type: "text",
    user_type: "visitor",
    time: "Today 11:52",
    status: "seen",
  },
  {
    id: 125,
    name: "Benedita Tavares",
    message:
      "Hello! I’m sorry to hear this. Could youshow me a screenshot about what happens?",
    message_type: "text",
    user_type: "agent",
    time: "Today 11:52",
    status: "seen",
  },
  {
    id: 127,
    name: "Benedita Tavares",
    message: "Sure. Taking a screenshot right now.",
    message_type: "text",
    user_type: "visitor",
    time: "Today 11:52",
    status: "seen",
  },
  {
    id: 124,
    name: "Benedita Tavares",
    message: chatimg,
    messagetext: "This is some test message",
    message_type: "text_image",
    user_type: "visitor",
    time: "Today 11:52",
    status: "seen",
  },
  {
    id: 134,
    name: "Benedita Tavares",
    message: chatimg,
    messagetext: "This is some test message",
    message_type: "text_image",
    user_type: "agent",
    time: "Today 11:52",
    status: "seen",
  },
  {
    id: 120,
    name: "Benedita Tavares",
    message: "Thanks you! I’m reporting this internally",
    message_type: "text",
    user_type: "agent",
    time: "Today 11:52",
    status: "seen",
  },
  {
    id: 129,
    name: "Benedita Tavares",
    message: chatimg,
    message_type: "image",
    user_type: "agent",
    time: "Today 11:52",
    status: "seen",
  },
  {
    id: 129,
    name: "Benedita Tavares",
    message: chatimg,
    message_type: "image",
    user_type: "visitor",
    time: "Today 11:52",
    status: "seen",
  },
  {
    id: 121,
    name: "Benedita Tavares",
    message: "Thanks you! I’m reporting this internally",
    message_type: "text",
    user_type: "visitor",
    time: "Today 11:52",
    status: "seen",
  },
  {
    id: 122,
    name: "Benedita Tavares",
    message: "Thanks you! I’m reporting this internally",
    message_type: "text",
    user_type: "agent",
    time: "Today 11:52",
    status: "seen",
  },
  {
    id: 121,
    name: "Benedita Tavares",
    message: "Thanks you! I’m reporting this internally",
    message_type: "text",
    user_type: "visitor",
    time: "Today 11:52",
    status: "seen",
  },
  {
    id: 122,
    name: "Benedita Tavares",
    message: "Thanks you! I’m reporting this internally",
    message_type: "text",
    user_type: "agent",
    time: "Today 11:52",
    status: "seen",
  },
  {
    id: 121,
    name: "Benedita Tavares",
    message: "Thanks you! I’m reporting this internally",
    message_type: "text",
    user_type: "visitor",
    time: "Today 11:52",
    status: "seen",
  },
  {
    id: 122,
    name: "Benedita Tavares",
    message: "Thanks you! I’m reporting this internally",
    message_type: "text",
    user_type: "agent",
    time: "Today 11:52",
    status: "seen",
  },
];

export const inprogressticket = [
  {
    id: 131,
    email: "xyz@xyz.com",
    Username: "Benedita Tavares",
    message:
      "Hello! I’m sorry to hear this. Could youshow me a screenshot about what happens?",
    status: "Active",
    newmsg: true,
  },
  {
    id: 132,
    email: "xyz@xyz.com",
    Username: "BeneditaTavares",
    message:
      "Hello! I’m sorry to hear this. Could youshow me a screenshot about what happens?",
    status: "Active",
    newmsg: true,
  },
  {
    id: 133,
    email: "xyz@xyz.com",
    Username: "Benedita Tavares",
    message:
      "Hello! I’m sorry to hear this. Could youshow me a screenshot about what happens?",
    status: "Active",
    newmsg: true,
  },
  {
    id: 134,
    email: "xyz@xyz.com",
    Username: "Zeeshan Ali",
    message:
      "Hello! I’m sorry to hear this. Could youshow me a screenshot about what happens?",
    status: "Active",
    newmsg: true,
  },
  {
    id: 135,
    email: "xyz@xyz.com",
    Username: " Benedita ",
    message:
      "Hello! I’m sorry to hear this. Could youshow me a screenshot about what happens?",
    status: "Active",
    newmsg: true,
  },
];
